### ISSUE TITLE
Middleclicking links doesn't open them in a new tab in the existing window

### ISSUE THREAD

**Issue by Mardeg** [grssam/Movie-critiques#1] opened 2013-02-16 19:43 UTC
I can't stand links forcing a new window to open on left click (especially when that causes the sidebar to IRC I have open to duplicate), so I'd like middleclicking the IMDB, Rotten Tomatoes, and Metacritic links for a movie to override that by opening them in a new tab in the existing window.
Interestingly on left click this extension ignores the about:config pref:
browser.link.open_newwindow.restriction
I set to 0 to force new windows into a new tab from webpages. Perhaps it could use that pref to determine how to open the links?

**Comment by grssam** [comment] 2013-02-16 20:10
Are you saying that the IMDB/Rotten Tomatoes or Meta Critic links open in a new window for you, instead of new tab ?

For me they open in new tab only.

**Comment by Mardeg** [comment] 2013-02-16 20:19
Correct, those links are definitely opening in a new window for me in my existing profile. I'll create a new one to check them in now.

**Comment by Mardeg** [comment] 2013-02-16 20:54
It's specific to Firefox 19 beta I can confirm so far, in a blank profile left clicking the links opens them in a new window.
In the same blank profile on nightly trunk builds, left clicking the links opens them in a new tab in the existing window.

In both cases, middleclicking the links does nothing. Would it be easier to change this issue into the left click problem that's version specific, or to go ahead and use this as it is to add a listener for middleclick that explicitly opens in a new tab?

**Comment by grssam** [comment] 2013-02-16 21:10
Okay, yes. Firefox 19 and below open it in new window. That's sad. I will try to fix it before the 19 release date.
Thanks for reporting it. I would have never caught it :)

**Comment by grssam** [comment] 2013-02-16 21:12
https://bugzilla.mozilla.org/show_bug.cgi?id=263433 is the cause which got fixed in Firefox 20

**Comment by grssam** [comment] 2013-07-09 09:19
Closing this as this is fixed now for 2 versions.

**Closed as completed by grssam** 2013-07-09 09:19 UTC
Labels: bug
